spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/site?useUnicode=true&characterEncoding=utf8&useSSL=true
    url: jdbc:mysql://172.21.139.13:3307/um?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    username: chaikuprod
    password: testchaiku